INSERT INTO [dbo].[ViewPoint]
           ([ViewPointId]
           ,[Name]
           ,[BeginDate]
           ,[EndDate]
           ,[Description])
     VALUES
           (NEWID()
           ,'Mainstream'
           ,'-12775000.0'
           ,'2459228.25'
           ,'The generally accepted academicly peer reviewed view on the years between 35000 BC to now')
GO

INSERT INTO [dbo].[ViewPoint]
           ([ViewPointId]
           ,[Name]
           ,[BeginDate]
           ,[EndDate]
           ,[Description])
     VALUES
           (NEWID()
           ,'New Chronology'
           ,'990245.0'
           ,'2459228.25'
           ,'The viewpoint of Fomenko, Nosovski, et al in which history repeats in cycles of roughly 300, 1000, 1800 years')
GO

